addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead       # builds perl from git
  - dev         # latest point release
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  global:
    - TEST_PARTITIONS=4
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=1
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=2
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=3
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=4
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps --coverage
before_script:
  - coverage-setup
script:
  - perl Build.PL
  - ./Build
  - prove -b -r -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
